name: Blue/Green Deployment and Testing

on:
    push:
        branches:
            - blue
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
    deploy-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Configure GitHub Identity
            run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"

          - name: Configure GitHub Pages
            uses: actions/configure-pages@v5
    
          - name: Test on blue version
            run: |
              RESPONSE=$(curl -s https://kateserna.github.io/asignacion_servidores_web/)
              echo "$RESPONSE" 
              if [[ "$RESPONSE" != *"Version: 2.0"* ]]; then
                echo "Test Success: Las pruebas pasaron exitosamente."
              else
                echo "Test Failed: Las pruebas fallaron, la verion blue no tiene el texto esperado."
                echo "Realizando rollback a la versión green."
                exit 1
              fi
    
          - name: Notify Test Success
            if: success()
            run: echo "La versión blue está lista para ser promovida."
    
          - name: Promote Blue to Green
            if: success()
            run: |
                echo "Git status"
                git status
                echo "Git fetch origin"
                echo "Git checkout green"
                git checkout green
                echo "Git merge origin blue"
                git merge origin blue
                echo "Git add ."
                echo "Git commit-m "Promote Blue to Green"
                echo "Git push origin green"
                echo "La versión Blue ha sido promovida a Green."

          - name: Upload files
            uses: actions/upload-pages-artifact@v3
            with:
              path: '.'  # Subir TODO el contenido de la raíz
    
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
                
