name: Blue/Green Deployment and Testing

on:
    push:
        branches:
            - blue
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
    deploy-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Configure GitHub Identity
            run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"

          - name: Configure GitHub Pages
            uses: actions/configure-pages@v5
    
          - name: Test on blue version
            run: |
                if grep "Version: 2.19" index.html; then
                    echo "Test Success: Las pruebas a blue pasaron exitosamente."
                    echo "La versión blue está lista para ser promovida."
                else
                    echo "Test Failed: Las pruebas  a blue fallaron, la versión blue no tiene el texto esperado."
                    exit 1
                fi
    
          - name: Promote blue to Green
            if: success()
            run: |
                git status
                git checkout green
                git merge origin blue
                git push
                echo "La versión Blue ha sido promovida a Green."

          - name: Test on green version
            run: |
                if grep "Version: 2.18" index.html; then
                    echo "Test Success: Las pruebas a green pasaron exitosamente."
                    echo "La versión green está lista para ser desplegada a GitHub Pages."
                else
                    echo "Test Failed: Las pruebas a green fallaron, la versión green no tiene el texto esperado."
                    echo "Realizando rollback a la versión green."
                    git reset --hard
                    git push origin green
                    echo "Rollback realizado. Saliendo con error!"
                    exit 1
                fi

          - name: Upload files
            uses: actions/upload-pages-artifact@v3
            with:
              path: '.'  # Subir TODO el contenido de la raíz
    
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
                
