name: Blue/Green Deployment and Testing

on:
    push:
        branches:
            - blue

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure GitHub Pages
            uses: actions/configure-pages@v5
    
          - name: Test on blue version
            run: |
              RESPONSE=$(curl -s https://kateserna.github.io/asignacion_servidores_web/)
              echo "$RESPONSE" 
              if [[ "$RESPONSE" != *"Version: 1.0"* ]]; then
                echo "Test Success: Las pruebas pasaron exitosamente."
              else
                echo "Test Failed: Las pruebas fallaron, la verion blue no tiene el texto esperado."
                echo "Realizando rollback a la versión green."
                exit 1
              fi
    
          - name: Notify Test Success
            if: success()
            run: echo "La versión blue está lista para ser promovida."
    
          - name: Promote Blue to Green
            if: success()
            run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git fetch
              git rebase --force green
              echo "La versión Blue ha sido promovida a Green."

          - name: Subir archivos
            uses: actions/upload-pages-artifact@v3
            with:
              path: '.'  # Subir TODO el contenido de la raíz
    
          - name: Desplegar en GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
                
