name: Blue/Green Deployment and Testing

on:
    push:
        branches:
            - blue

jobs:
    deploy-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure GitHub Pages
            uses: actions/configure-pages@v5
    
          - name: Test on blue version
            run: |
              RESPONSE=$(curl -s https://kateserna.github.io/asignacion_servidores_web/)
              echo "$RESPONSE" 
              if [[ "$RESPONSE" != *"Creada por:"* ]]; then
                echo "Test Success: Las pruebas pasaron exitosamente."
              else
                echo "Test Failed: Las pruebas fallaron, la verion blue no tiene el texto esperado."
                exit 1
              fi
    
          - name: Notify Test Success
            if: success()
            run: echo "La versi칩n blue est치 lista para ser promovida."
    
          - name: Rollback to green
            if: failure()
            run: echo "Las pruebas fallaron. Realizando rollback a la versi칩n green."

          - name: Promote Blue to Green
            if: success()
            run: |
              git checkout green
              git pull origin green
              git merge blue
              git push origin green
              echo "La versi칩n Blue ha sido promovida a Green."
